name: build_Qt5.15_MinGW810_64

on: workflow_dispatch
#on: [push, pull_request]

env:
  QT_VERSION: 5.15.18
  QT_VERSION2: 5.15
  FILE_NAME: shared-Debug-Release_mingw810_64

jobs:
  windows_mingw64_shared_debug_release:
    runs-on: windows-latest

    steps:
    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v4

    # 安装python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        architecture: 'x64'

    # 安装 Perl    
    - name: Setup Perl
      run: |
        cd ..  #Directory: D:\a\buildQt
        curl -L -o strawberry-perl-64bit-portable.zip https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_54001_64bit_UCRT/strawberry-perl-5.40.0.1-64bit-portable.zip
        unzip -q strawberry-perl-64bit-portable.zip -d ./Strawberry

    # 安装 MinGW810_64    
    - name: Setup MinGW64
      run: |
        cd ..  #Directory: D:\a\buildQt
        mkdir -p mingw64
        curl -L -o 8.1.0-release-posix-seh.7z https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_mingw81/qt.tools.win64_mingw810/8.1.0-1-202411201005x86_64-8.1.0-gdb-11.2.0-release-posix-seh-rt_v6-rev0.7z
        7z x D:\a\buildQt\8.1.0-release-posix-seh.7z -oD:\a\buildQt\mingw64

    # 构建Qt
    - name: Build Qt
      run: |
        #ls     #Directory: D:\a\buildQt\buildQt(即仓库目录)
        #D:\a\buildQt                                上级目录，这里当做根目录
        #D:\a\buildQt\Qt                             Qt目录
        #D:\a\buildQt\Qt\${{env.QT_VERSION}}         Qt目录源代码和build文件夹存放目录
        #D:\a\buildQt\Qt\${{env.QT_VERSION}}-shared  Qt安装目录
        
        # 创建文件夹
        cd ..  #Directory: D:\a\buildQt
        mkdir -p Qt

        # 创建文件夹
        cd Qt   #Directory: D:\a\buildQt\Qt
        mkdir -p ${{env.QT_VERSION}}
        mkdir -p ${{env.QT_VERSION}}-shared

        # 下载源代码并解压，源代码目录D:\a\buildQt\Qt\${{env.QT_VERSION}}\XXX
        curl -L -o qt-everywhere-opensource-src.zip https://download.qt.io/archive/qt/${{env.QT_VERSION2}}/${{env.QT_VERSION}}/single/qt-everywhere-opensource-src-${{env.QT_VERSION}}.zip
        unzip -q qt-everywhere-opensource-src.zip -d ./${{env.QT_VERSION}}

        # 设置Qt源代码目录
        $srcQt = "D:\a\buildQt\Qt\${{env.QT_VERSION}}\qt-everywhere-src-${{env.QT_VERSION}}"

        # 补充设置qtbase\bin和gnuwin32\bin
        $env:PATH = "$srcQt\qtbase\bin;$srcQt\gnuwin32\bin;$env:PATH"

        # 设置安装文件夹目录
        $installDir = "D:\a\buildQt\Qt\${{env.QT_VERSION}}-shared\mingw810_64"

        # 设置build文件夹目录
        $buildDir = "D:\a\buildQt\Qt\${{env.QT_VERSION}}\build-mingw810_64"

        # 创建并进入构建目录
        if (Test-Path $buildDir) { Remove-Item -Recurse -Force $buildDir }
        New-Item -ItemType Directory -Path $buildDir -Force | Out-Null
        Set-Location $buildDir

        # Configure
        & "$srcQt\configure.bat" -shared -debug-and-release -prefix $installDir -nomake examples -nomake tests -skip qtwebengine -opensource -confirm-license -qt-libpng -qt-libjpeg -qt-zlib -qt-pcre -qt-freetype -schannel -opengl desktop -platform win32-g++

        # 编译、安装
        mingw32-make -j$env:NUMBER_OF_PROCESSORS
        mingw32-make install

        # 复制qt.conf
        Copy-Item -Path "${{github.workspace}}\qt.conf" -Destination "$installDir\bin" -Force

    # 打包
    - name: Package binaries
      run: |
        #ls     #Directory: D:\a\buildQt\buildQt(即仓库目录)
        7z a Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z ../Qt/${{env.QT_VERSION}}-shared -mx=9

    # 上传
    - uses: actions/upload-artifact@v4
      with:
        name: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}
        path: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z
